services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dyndb
    hostname: dynamodb
    restart: always
    volumes:
      - ./.tmp/dynamodb:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
